config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :presents
  get '/:user_id/presents/', to: 'presents#index', as: 'present_list'

  # Authentication by the power of omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/facebook', as: 'login'
end

app/models/present.rb
class Present < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :presents

  def self.omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.token = auth.credentials.token
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_authentication

  def check_authentication
    redirect_to login_url if session[:user_id].blank?
  end

  helper_method :current_user
  def current_user
    @user ||= User.find_by(id: session[:user_id])
    @user
  end
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_action :set_present, only: [:show, :edit, :update, :destroy]
  before_action :check_authorisation, only: [:show, :edit, :update, :destroy]

  # GET /presents
  # GET /presents.json
  def index
    # set user to either the one specified in the url or the current user
    user = (url_user.present? ? User.find(url_user) : current_user)
    @presents = Present.where(user: user)
  end

  # GET /presents/1
  # GET /presents/1.json
  def show
  end

  # GET /presents/new
  def new
    @present = Present.new
  end

  # GET /presents/1/edit
  def edit
  end

  # POST /presents
  # POST /presents.json
  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if create_present
        format.html { redirect_to presents_url, notice: 'Present was successfully created.' }
        format.json { render :show, status: :created, location: @present }
      else
        format.html { render :new }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presents/1
  # PATCH/PUT /presents/1.json
  def update
    respond_to do |format|
      if @present.update(present_params)
        format.html { redirect_to presents_url, notice: 'Present was successfully updated.' }
        format.json { render :show, status: :ok, location: @present }
      else
        format.html { render :edit }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1
  # DELETE /presents/1.json
  def destroy
    @present.destroy
    respond_to do |format|
      format.html { redirect_to presents_url, notice: 'Present was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def create_present
    @present.user = current_user
    @present.save
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_present
    @present = Present.find(params[:id])
  end

  def check_authorisation
    redirect_to root_url unless @present.user == current_user
  end

  def url_user
    return present_list_params['user_id'] if /\A\d+\z/.match(present_list_params['user_id'])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def present_params
    params.require(:present).permit(:title, :description, :url, :price)
  end

  def present_list_params
    params.permit(:user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_authentication

  def create
    user = User.omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Presents</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/presents/_form.html.erb
<%= form_for(@present) do |f| %>
  <% if @present.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@present.errors.count, "error") %> prohibited this present from being saved:</h2>

      <ul>
      <% @present.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="actions form-group">
    <%= f.submit 'Buy me things', class: "btn btn-default" %>
  </div>
<% end %>

app/views/presents/edit.html.erb
<h1>Editing Present</h1>

<%= render 'form' %>

<%= link_to 'Show', @present %> |
<%= link_to 'Back', presents_path %>

app/views/presents/index.html.erb
<h1>Presents for <%= current_user.name %></h1>

<%- unless notice.blank? %>
<div class="alert alert-warning col-sm-8">
  <p id="notice"><%= notice %></p>
</div>
<%- end %>

<%= link_to 'New Present', new_present_path, class: 'btn btn-primary btn-lg new-present' %>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th class="col-md-2">Title</th>
      <th class="col-md-2">Price</th>
      <th class="col-md-2"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @presents.each do |present| %>
      <tr>
        <td><%= link_to present.title, present %></td>
        <td><%= link_to (present.price.present? ? number_to_currency(present.price) : '~'), present %></td>
        <td><%= link_to 'Edit', edit_present_path(present), class: 'btn btn-primary btn-xs edit-link' %></td>
        <td><%= form_tag(present, method: 'delete') do
                  submit_tag 'Delete', class: 'btn btn-danger btn-xs delete-link',
                              data: { confirm: 'Are you sure?' }
                end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/presents/new.html.erb
<h1>New Present</h1>

<%= render 'form' %>

<%= link_to 'Back', presents_path %>

app/views/presents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @present.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @present.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @present.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @present.price %>
</p>

<%= link_to 'Edit', edit_present_path(@present) %> |
<%= link_to 'Back', presents_path %>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome <%= current_user.name %></h1>
<ul class="list-unstyled">
  <li><%= link_to 'Add a new present', new_present_path %></li>
  <li><%= link_to 'Your presents', presents_path %></li>
</ul>

<h2>Everyone using this application</h2>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, present_list_path(user.id) %></li>
  <% end %>
</ul>